/*
 * generated by Xtext
 */
package org.xtext.homeautomation.ui.contentassist

import org.xtext.homeautomation.ui.contentassist.AbstractRulesProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class RulesProposalProvider extends AbstractRulesProposalProvider {
}
