/*
 * generated by Xtext
 */
package org.xtext.ruleengine.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RuleEngineUiModule extends org.xtext.ruleengine.ui.AbstractRuleEngineUiModule {
	public RuleEngineUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
