/*
 * generated by Xtext
 */
package org.xtext.ruleengine;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RuleEngineRuntimeModule extends org.xtext.ruleengine.AbstractRuleEngineRuntimeModule {

}
