/*
* generated by Xtext
*/
package org.xtext.ruleengine;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class RuleEngineStandaloneSetup extends RuleEngineStandaloneSetupGenerated{

	public static void doSetup() {
		new RuleEngineStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

