/*
 * generated by Xtext
 */
package org.xtext.homeautomation;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RulesRuntimeModule extends org.xtext.homeautomation.AbstractRulesRuntimeModule {

}
